#!/bin/bash

CA_BASEDIR=$(dirname $0)

if [ -z "$SUBVERB" -a -x "$CA_BASEDIR/subverb/subverb" ]; then
	SUBVERB="$CA_BASEDIR/subverb/subverb"
fi

if [ -z "$SUBVERB" ]; then
	SUBVERB=$(which subverb)
fi

if [ -z "$SUBVERB" ]; then
	echo "subverb not found"
	exit 1
fi

echo running suberb in dev-mode in $CA_BASEDIR 1>&2
export CAUTL_SYSCONFIG=$CA_BASEDIR/etc/cautl
export CAUTL_SHARED_DIR=$CA_BASEDIR/share
export CAUTL_DOC_DIR=$CA_BASEDIR/doc
export CAUTL_LIB_DIR=$CA_BASEDIR/lib
export CAUTL_SUBCMD_DIR=$CA_BASEDIR/lib/subverb
export PATH=$PATH:bin/

. $SUBVERB

